### ISSUE TITLE
Please make Functional App for example and clone.

### ISSUE THREAD

**Issue by wellington1993** [gdi/ruby-zimbra#4]
@spikex Do you make me a favor?,  I am recent start on Ruby Rails programming. On rails clean and new App, what is first stage to require and use this Gem, for example simple rails app to Create zimbra account.

**Comment by spikex** [comment]
First add:

```
gem 'zimbra'
```

to your `Gemfile` and run `bundle install`

Then you need to configure the API. create `config/initializers/zimbra.rb` and put:

```ruby
Zimbra.admin_api_url = 'https://zimbra.example.com:7071/service/admin/soap'
Zimbra.account_api_url = 'https://zimbra.example.com/service/soap'
Zimbra.login('admin@example.com','your admin password here')
```

(It would be safer to put your password in an environment variable or a config file that's on checked in to Git. Google for lots of examples of how you do that.)

Then you can create an account as follows:

```ruby
account_name = 'bob@example.com'
password = 'Something Good'
first_name = 'Bob'
last_name = 'Smith'

zimbra_params = { 
   name: account_name,
   password: password,
   attributes: {displayName:  "#{first_name} #{last_name}", gn: first_name, sn: last_name}
}
account = Zimbra::Account.create(zimbra_params)
``` 

For the *attributes* to work, you need to my patch, otherwise you can't set the name through the API. So, either my pull request needs to be merged or you need to use my fork:

```
gem 'zimbra', github: 'spikex/ruby-zimbra', branch: 'master'
```

**Comment by wellington1993** [comment]
Thanks!
